### PR TITLE
Update Terms and Definitions chapter

### PR DESCRIPTION
**Pull request by bact**
- Use text from Bob's Word doc 2024-07-22

### CODE REVIEW

**Comment by bact** [comment]
Just in case, a paragraph referring ISO/IEC terms databases, removed in this update, is here:

```Markdown
ISO and IEC maintain terminological databases for use in standardization at the
following addresses:

- ISO Online browsing platform: available at
  [www.iso.org/obp](https://www.iso.org/obp)
- IEC Electropedia: available at
  [www.electropedia.org](http://www.electropedia.org/)
```

**Review by bobmartin3000 — APPROVED** [review]
LGTM

**Review by zvr — CHANGES_REQUESTED** [review]
These look like they came from SPDXv2.

In SPDXv3 we don't have Package, File, Snippet "sections" in the spec

**Comment by bobmartin3000** [comment]
I may have grabbed the wrong set.  Sorry.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Alexios Zavras (zvr) ***@***.***>
Sent: Friday, August 9, 2024 10:11:09 PM
To: spdx/spdx-spec ***@***.***>
Cc: Robert A Martin ***@***.***>; Comment ***@***.***>
Subject: [EXT] Re: [spdx/spdx-spec] Update Terms and Definitions chapter (PR #1004)

@zvr requested changes on this pull request. These look like they came from SPDXv2. In SPDXv3 we don't have Package, File, Snippet "sections" in the spec — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving


@zvr requested changes on this pull request.

These look like they came from SPDXv2.

In SPDXv3 we don't have Package, File, Snippet "sections" in the spec

**Comment by goneall** [comment]
@bobmartin3000 - We're blocked on this update - can you provide a correct version for the spec?  If we don't have it, can we publish the PDF without it?

**Comment by kestewart** [comment]
Discussion is we'll go with what was in original ISO submission for 3.0.1;  unless Bob is able to put in an updated PR for the different terms.

**Comment by bobmartin3000** [comment]
Hope to send shortly

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: goneall ***@***.***>
Sent: Saturday, August 10, 2024 1:04:08 PM
To: spdx/spdx-spec ***@***.***>
Cc: Robert A Martin ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [spdx/spdx-spec] Update Terms and Definitions chapter (PR #1004)

@bobmartin3000 - We're blocked on this update - can you provide a correct version for the spec? If we don't have it, can we publish the PDF without it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving


@bobmartin3000<https://github.com/bobmartin3000> - We're blocked on this update - can you provide a correct version for the spec? If we don't have it, can we publish the PDF without it?

**Comment by bobmartin3000** [comment]
Looks like we never made one unique to 3.0.  Use the one from ISO.

Bob

From: Robert A Martin ***@***.***>
Date: Saturday, August 10, 2024 at 2:04 PM
To: spdx/spdx-spec ***@***.***>, spdx/spdx-spec ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [EXT] Re: [spdx/spdx-spec] Update Terms and Definitions chapter (PR #1004)
Hope to send shortly

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: goneall ***@***.***>
Sent: Saturday, August 10, 2024 1:04:08 PM
To: spdx/spdx-spec ***@***.***>
Cc: Robert A Martin ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [spdx/spdx-spec] Update Terms and Definitions chapter (PR #1004)

@bobmartin3000 - We're blocked on this update - can you provide a correct version for the spec? If we don't have it, can we publish the PDF without it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving


@bobmartin3000<https://github.com/bobmartin3000> - We're blocked on this update - can you provide a correct version for the spec? If we don't have it, can we publish the PDF without it?

**Comment by bobmartin3000** [comment]
We can use the ISO one for now.

From: goneall ***@***.***>
Date: Saturday, August 10, 2024 at 1:04 PM
To: spdx/spdx-spec ***@***.***>
Cc: Robert A Martin ***@***.***>, Mention ***@***.***>
Subject: [EXT] Re: [spdx/spdx-spec] Update Terms and Definitions chapter (PR #1004)
@bobmartin3000 - We're blocked on this update - can you provide a correct version for the spec? If we don't have it, can we publish the PDF without it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving


@bobmartin3000<https://github.com/bobmartin3000> - We're blocked on this update - can you provide a correct version for the spec? If we don't have it, can we publish the PDF without it?

**Comment by kestewart** [comment]
Ok,  closing this.   We'll use the one from the ISO version, which is in the repo now.    Closing this.

**Pull request closed without merging**
