### PR TITLE
CI for v3.0.1 publication

### LINKED ISSUE #996: Advertise version: MAJOR.MINOR.PATCH or MAJOR.MINOR ?
Continuing discussion from [SPDX Tech Team Meeting 2024-07-16](https://github.com/spdx/meetings/pull/745):

From the ontology point of view:
- An object `https://spdx.org/a/3.0.x/b` is not the same as an object `https://spdx.org/a/3.0.y/b`

For spec publication:
- If using MAJOR.MINOR.PATCH, we can make:
  - `v3.0` as an alias that point to the latest version of `v3.0.x` (for example, `v3.0.1`)
  - `v3` as an alias that point to the latest version of `v3.x` (for example, `v3.0`)
  - For example,
    - we can set `mike alias -u v3.0.1 v3.0 v3 latest` (set "v3.0", "v3", and "latest" as aliases for "v3.0.1")
    - then when we have 3.1, we can set `mike alias -u v3.1 v3 latest` (set "v3" and "latest" as aliases for "v3.1")
    - `v3.0` will still redirect to `v3.0.1`, while `v3` will now redirect to `v3.1`
- If using MAJOR.MINOR,
  - Any patch update for `v3.0` (v3.0.1, v3.0.2, etc) will be publish under `v3.0`
  - (at 3.0.0) `mike alias -u v3.0 v3 latest`
  - (at 3.0.1) `mike alias -u v3.0 v3 latest` (keep using "v3.0")
  - (at 3.0.2) `mike alias -u v3.0 v3 latest` (keep using "v3.0")
  - (at 3.1) `mike alias -u v3.1 v3 latest` (change to "v3.1")

Current decision is to use MAJOR.MINOR.PATCH.

See also
- https://github.com/spdx/spdx-3-model/issues/733
- https://github.com/spdx/spdx-3-model/pull/800
- https://github.com/spdx/spdx-spec/pull/936

### LINKED ISSUE #1018: Spec website: How do we like the URL aliases to work?
As it is difficult to explain for me, so I'm setting up a test website here for illustration.
(The test website is marked with "DRAFT (TEST-WEBSITE)" at the top and the bottom to avoid confusion)

We will use the URL of the test spec website https://bact.github.io/spdx-spec/
in place of
https://spdx.github.io/spdx-spec/ here for the purpose of discussion/demonstration.

Once 3.0.1 released, PR #1015 will made these following redirections:

### 1) Default redirection

If the user doesn't specify a version in the URL, we will bring them to the latest version:

https://bact.github.io/spdx-spec/  --> https://bact.github.io/spdx-spec/v3.0.1/

Do we like to have it like this?
(you can try clicking on these URLs)

https://spdx.github.io/spdx-spec/ currently redirects to https://spdx.github.io/spdx-spec/v3.0/

### 2) Alias

These following URLs will redirect to https://bact.github.io/spdx-spec/v3.0.1/ :

- https://bact.github.io/spdx-spec/latest/
- https://bact.github.io/spdx-spec/v3.0/
- https://bact.github.io/spdx-spec/v3-draft/
- https://bact.github.io/spdx-spec/v3.0-RC1/
- https://bact.github.io/spdx-spec/v3.0-RC2/

(Once we have 3.0.2, all of above will redirect instead to 3.0.2.
Once we have 3.1, "latest" will redirect to 3.1; but "v3.0*" will still redirect to the latest 3.0.x)

Do we like to have those URLs behave like that?

- latest currently redirects to v2.3 - try https://spdx.github.io/spdx-spec/latest/
- v3.0 currently contains v3.0 content
- v3-draft currently redirects to v3.0 - try https://spdx.github.io/spdx-spec/v3-draft/
- v3.0-RC1 never exists
- v3.0-RC2 currently redirects to v3.0 - try https://spdx.github.io/spdx-spec/v3.0-RC2/

### 3) Versions available to choose from the UI

Only **the latest patch versions for each minor version** will be displayed on the dropdown list.

dropdown

Is this something we imagine?
Or do we also need v3.0 (v3.0.0) in the dropdown as well?

(for v2, we only have v2.3 and v2.2.2)

----

Feel free to suggest something else. Comments will inform changes to PR #1015. Thank you.

Note: Since, from the above settings, "v3.0" will be use as an alias, if we still like to get access to the original v3.0 (v3.0.0) content, we can apply PR #994 to republish v3.0 as v3.0.0.

----

Additional requirements

- #1069

### LINKED ISSUE #1069: Redirection requirement of v3.0 URL -> latest URL
From Tech call 2024-08-13

These URLs (not an exhaustive list):

- https://spdx.github.io/spdx-spec/v3.0/model/Core/Classes/CreationInfo/
- https://spdx.github.io/spdx-spec/v3.0/model/Software/Classes/Sbom/
- https://spdx.github.io/spdx-spec/v3.0/model/Software/Classes/Sbom/
- https://spdx.github.io/spdx-spec/v3.0/model/Software/Classes/Package/

should be redirected to these URLs or displayed the content of these URLs:

- https://spdx.github.io/spdx-spec/v3.0.1/model/Core/Classes/CreationInfo/
- https://spdx.github.io/spdx-spec/v3.0.1/model/Software/Classes/Sbom/
- https://spdx.github.io/spdx-spec/v3.0.1/model/Software/Classes/Sbom/
- https://spdx.github.io/spdx-spec/v3.0.1/model/Software/Classes/Package/
(or the latest version)

The URLs are used by "Framing Software Component Transparency: Establishing a Common Software Bill of Materials (SBOM)" and few other whitepapers to be released in a future.

### For properties with "new" name

In v3.0.1, there're [several fixes in property names](https://github.com/spdx/spdx-3-model/blob/main/CHANGELOG.md). For example, v3.0.0 `imports` is v3.0.1 `import`. Because of that:

- Standard mkdocs redirection will redirects "v3.0/imports/" to non-exist "v3.0.1/imports/", resulting 404
- With [mkdocs-redirects](https://github.com/mkdocs/mkdocs-redirects) plugin, we may able to define a map between `imports` and `import` - has to explore
  - With some configuration work, we may able to redirect "v3.0/imports/" to  "v3.0.1/import/"
  - UPDATE: mkdocs-redirects works within the same spec version but not across spec versions. So we have to come up with our own script.

### PR DESCRIPTION
**Pull request by bact**
## Summary

Updated CI for v3.0.1 publication and new spec-parser directory structure

- [x] Setup redirection 
  - [x] Website: Decision - 3.0 will redirect to the latest. https://github.com/spdx/spdx-spec/issues/1018#issuecomment-2313112740
  - [x] Schema/RDF: 3.0 redirection/alias https://github.com/spdx/spdx-spec/issues/996#issuecomment-2313141592
  - [x] Setup case-specific redirections (for name differences between 3.0.0 and 3.0.1) #1069
- [ ] Update generation dir names #1066
  - Once new spec-parser is merged, update `RDF_BASE_DIR` and `MKDOCS_BASE_DIR` values in `.github/workflows/publish_v3.yml` to "rdf" and "mkdocs" (see comments at Lines 24-25)
- [ ] Update checkout branch/tag names #1092
  - Once new branch/tag release names available, update `REF_SPEC`, `REF_MODEL`, and `REF_PARSER` values  in `.github/workflows/publish_v3.yml` (see Lines 14-16)

Will resolve #996, resolve #1018, resolve #1069

## Removal of old workflows

This PR also remove `.github/workflows/publish.yml` and `.github/workflows/publish_common.yml` as they are no longer in use for v3 publication.

All of them are still available in v2 branches.
For example, https://github.com/spdx/spdx-spec/tree/development/v2.3/.github/workflows

## Main workflow steps

Below are steps in `.github/workflows/publish_v3.yml`.
The big ones are the last two where they do extra work to keep old URLs working. 
The YAML file has more comments.

1. Checkout spdx-spec
1. Checkout spdx-3-model
1. Checkout spec-parser
1. Install pre-requisites for spdx-spec
1. Install pre-requisites for spec-parser
1. Build model files
    - Using spec-parser
1. Create directories for model (MkDocs) and RDF files
1. Copy JSON annotations
1. Copy JSON-LD context and RDFs
1. Generate JSON schema
1. Copy model files and file list for MkDocs
1. Set Git identity
1. Sync GitHub Pages
1. Build complete MkDocs configuration
    - In this step, it combines model file list (mkdocs-files.yml, generated by spec-parser) with mkdocs.yml (it replaces "__MODEL_PLACEHOLDER__" string with the content of mkdocs-files.yml)
1. Deploy and set aliases
1. Copy JSON annotations, JSON schema, JSON-LD context, and RDFs to alias directories
    - This step creates copies of annotations/schema/RDFs to all alias directories,
      so it can be accessible from all old URLs for backward compatibility.
    - For example,
        - https://spdx.github.io/spdx-spec/v3.0/model/schema.json
        - https://spdx.github.io/spdx-spec/v3.0.1/rdf/schema.json
      will all accessible and have the same content.
1. Make redirections (for renamed model elements and moved annexes)
    - This step make old names like [`imports`](https://bact.github.io/spdx-spec/v3.0/model/Core/Properties/imports/) to redirect to its new name at [`import`](https://bact.github.io/spdx-spec/v3.0.1/model/Core/Properties/import/).
    - It reads a list of redirect mapping from etc/redirect-map.csv;
      First value is 'from' (source), second value is 'to' (target).
    - 'from' and 'to' values will be inserted into the redirection HTML template etc/redirect-template.html
    - to create HTML files with 'from' name that will refresh the browser to the 'to'.

## Demo

The demo of this workflow is at https://bact.github.io/spdx-spec/

To see what the workflow will look like when running, see a log at
https://github.com/bact/spdx-spec/actions/runs/10716224938
(this is deployed on my own personal repo, not the spdx one).

### Redirection tests

To illustrates the redirection, here are some example.

- Versions
  - [/ (root)](https://bact.github.io/spdx-spec/latest/) --> [v3.0.1/](https://bact.github.io/spdx-spec/v3.0.1/)
  - [latest](https://bact.github.io/spdx-spec/latest/) --> [v3.0.1/](https://bact.github.io/spdx-spec/v3.0.1/)
  - [v3.0](https://bact.github.io/spdx-spec/v3.0) --> [v3.0.1/](https://bact.github.io/spdx-spec/v3.0.1/)
  - [v3.0/model/Software/Classes/File/](https://bact.github.io/spdx-spec/v3.0/model/Software/Classes/File/) --> [v3.0.1/model/Software/Classes/File/](https://bact.github.io/spdx-spec/v3.0.1/model/Software/Classes/File/)
- 3.0.0 vs 3.0.1 name differences in model
  - [v3.0/model/Software/Properties/contentType/](https://bact.github.io/spdx-spec/v3.0/model/Software/Properties/contentType/) --> [v3.0.1/model/Core/Properties/contentType/](https://bact.github.io/spdx-spec/v3.0.1/model/Core/Properties/contentType/)
  - [v3.0/model/Build/Properties/parameters/](https://bact.github.io/spdx-spec/v3.0/model/Build/Properties/parameters/) --> [v3.0.1/model/Build/Properties/parameter/](https://bact.github.io/spdx-spec/v3.0.1/model/Build/Properties/parameter/)
  - [v3.0.1/model/Core/Properties/imports/](https://bact.github.io/spdx-spec/v3.0.1/model/Core/Properties/imports/) --> [v3.0.1/model/Core/Properties/import/](https://bact.github.io/spdx-spec/v3.0.1/model/Core/Properties/import/)
- Moved docs
  - [v3.0/introduction/](https://bact.github.io/spdx-spec/v3.0/introduction/) --> [v3.0.1/front/introduction/](https://bact.github.io/spdx-spec/v3.0.1/front/introduction/) 
  - [v3.0/normative-references/](https://bact.github.io/spdx-spec/v3.0/normative-references/) --> [v3.0.1/references/](https://bact.github.io/spdx-spec/v3.0.1/references/)
  - [v3.0/annexes/RDF-object-model-and-identifier-syntax/](https://bact.github.io/spdx-spec/v3.0/annexes/RDF-object-model-and-identifier-syntax/) -> [v3.0.1/annexes/rdf-model/](https://bact.github.io/spdx-spec/v3.0.1/annexes/rdf-model/)
  - [v3.0/annexes/getting-started/](https://bact.github.io/spdx-spec/v3.0/annexes/getting-started/) -> https://github.com/spdx/using/blob/main/docs/getting-started.md/ (External)

### CODE REVIEW

**Comment by bact** [comment]
@licquia here's the new CI for 3.0.1. Please kindly review.

Most of the configurations are at Lines 14-27 of .github/workflows/publish_v3.yml 
This is designed to work with new spec-parser output directory structure (change Lines 23-24 for new dir structure).

The last step is to handle [few name differences between 3.0 and 3.0.1](https://github.com/spdx/spdx-3-model/blob/main/CHANGELOG.md),
so links like https://spdx.github.io/spdx-spec/v3.0/model/Core/Properties/imports/ will not break.

The step before last is to handle URL from old spec-parser output dir structure,
so links like https://spdx.github.io/spdx-spec/v3.0/model/schema.json will still working,
in parallel with the new link https://spdx.github.io/spdx-spec/v3.0/rdf/schema.json

**Comment by bact** [comment]
Redirection tests
- Versions
  - https://bact.github.io/spdx-spec/v3.0/ --> https://bact.github.io/spdx-spec/v3.0.1/
  - https://bact.github.io/spdx-spec/latest/ --> https://bact.github.io/spdx-spec/v3.0.1/
  - https://bact.github.io/spdx-spec/v3.0/model/Core/Vocabularies/RelationshipType/ --> https://bact.github.io/spdx-spec/v3.0.1/model/Core/Vocabularies/RelationshipType/
- 3.0.0 vs 3.0.1
  - https://bact.github.io/spdx-spec/v3.0/model/Software/Properties/contentType/ --> https://bact.github.io/spdx-spec/v3.0.1/model/Core/Properties/contentType/
  - https://bact.github.io/spdx-spec/v3.0/model/Build/Properties/parameters/ --> https://bact.github.io/spdx-spec/v3.0.1/model/Build/Properties/parameter/
  - https://bact.github.io/spdx-spec/v3.0/model/Core/Properties/imports/ --> https://bact.github.io/spdx-spec/v3.0.1/model/Core/Properties/import/
  - https://bact.github.io/spdx-spec/v3.0.1/model/Core/Properties/imports/ --> https://bact.github.io/spdx-spec/v3.0.1/model/Core/Properties/import/
- Avoiding 404 
  - https://bact.github.io/spdx-spec/v3.0.1/model/ --> https://bact.github.io/spdx-spec/v3.0.1/model/Core/Core/
  - https://bact.github.io/spdx-spec/v3.0.1/model/Core/ --> https://bact.github.io/spdx-spec/v3.0.1/model/Core/Core/
  - https://bact.github.io/spdx-spec/v3.0.1/model/Lite --> https://bact.github.io/spdx-spec/v3.0.1/model/Lite/Lite/

**Comment by bact** [comment]
Ping @zvr - I have to add `index.md` back at the `docs` root level here.

Because without it, URLs like https://spdx.github.io/spdx-spec/v3.0/ and https://spdx.github.io/spdx-spec/v3.0.1/ will return 404 File Not Found as there is no `index.html` being generated. MkDocs also use docs/index.md as an entry point.

Not sure if this will affect the ISO/OMG submissions or not, we will figure out, but in any case the index.md really has be at that exact location :(

**Review by goneall — APPROVED** [review]
I didn't see any issue - but it is a very large set of changes so some additional reviews would be helpful.

The redirects-map probably needs another set of eyes as well as the CI logic

**Comment by bact** [comment]
Thank you. It is really a huge changeset.

I just added comments explaining few steps more in the publish_v3.yml to facilitate the review.

**Review by zvr — APPROVED** [review]

**Pull request merged**
