### PR TITLE
Update Spec Version to 2.3, fix comma typo

### PR DESCRIPTION
**Pull request by davaya**

### CODE REVIEW

**Review by goneall — APPROVED** [review]

**Comment by goneall** [comment]
Thanks @davaya - good catch.  Could you add a sign-off in the commit record (see https://github.com/spdx/spdx-spec/runs/6869800622?check_suite_focus=true)

**Comment by davaya** [comment]
If I'm reading this correctly, the only way I can fix the check is to do a dangerous rebase.

Instead, you could close this PR and add the comma yourself.  Much safer.  I don't have any pride of ownership or intellectual property claim on that comma; it's all yours.

**Comment by goneall** [comment]
@tsteenbe Any issue if I override and accept this PR?

**Comment by goneall** [comment]
I found another typo or copy/paste error - so I included this change in PR #717 

Closing this PR.

**Pull request closed without merging**
