### PR TITLE
Add getting started annex

### PR DESCRIPTION
**Pull request by JPEWdev**
Adds an Annex that walks through writing a JSON-LD SPDX document line by line

### CODE REVIEW

**Review by kestewart — APPROVED** [review]
This is great Joshua!

Thank you very much for pulling this together.

**Comment by kestewart** [comment]
@goneall, @rnjudge - can you please review & merge if you're good with this too.

**Comment by rnjudge** [comment]
@JPEWdev did you mean to include changes to [.github/workflows/validate_examples.yml](https://github.com/spdx/spdx-spec/pull/906/files#diff-33a69fa65ae0df7834d246f1f23d43d3b48cea3123b4ade336d84f60dd990b3d) in this PR?

**Review by goneall — APPROVED** [review]
LGTM

**Pull request merged**
