### PR TITLE
schema: Fix typos and clarify documentDescribes array

### PR DESCRIPTION
**Pull request by lhh**
Signed-off-by: Lon Hohberger <lhh@redhat.com>

### CODE REVIEW

**Comment by goneall** [comment]
@lhh First - thanks for raising this issue and helping with the Python libraries!

The schema is actually generated from the [SPDX OWL Ontology](https://github.com/spdx/spdx-spec/blob/development/v2.2.2/ontology/spdx-ontology.owl.xml).

I took a look and indeed these typos are present in the ontology file (which is just slightly embarrassing since I maintain that file).

The descriptions should just be copy/pasted from the spec itself, but something in this rather manual process seems to have gone amiss.

Let's leave this PR open - I'm planning to update the OWL document for a couple other issues/PR's in the next 2-3 weeks and I'll fix these at that time.  I'll assign myself to the PR to follow-up.

Just a note - @zvr is working on some automation for 3.0 that should make these issues much less likely - not to mention saving me a bunch of time :)

**Comment by lhh** [comment]
Sounds good, thanks!

**Comment by lhh** [comment]
Apart from "this should have been auto-generated", am I correct with the assumption concerning the documentDescribes field?

**Comment by goneall** [comment]
@lhh Sorry for the delayed response - the `documentDescribes` property represents all package/file/snippets which are the target elements of a `DESCRIBES` relationship from the SPDX Document (see the [relationships section](https://spdx.github.io/spdx-spec/relationships-between-SPDX-elements/) for a description of `DESCRIBES`).  

Issue #533 is a related issue.

**Comment by lhh** [comment]
Thanks for the information!

**Comment by kestewart** [comment]
Typos need to be fixed in OWL document and regenerated.  @goneall on point to fix this.

**Comment by kestewart** [comment]
@goneall - can you please generate this file, so we can apply.

**Comment by goneall** [comment]
I just generated a schema which includes fixes for these typos: PR #631 

@kestewart If PR #631 is OK - this PR can be closed and PR #631 can be merged.

**Comment by kestewart** [comment]
Confirm that https://github.com/spdx/spdx-spec/pull/631 has applied the fixes denoted here.    Closing this one off.

**Pull request closed without merging**
