### PR TITLE
Add <del> (~~strikethrough~~) support

### LINKED ISSUE #929: Wrong display for strikethrough text
https://spdx.github.io/spdx-spec/v3.0/annexes/diffs-from-previous-editions/

File diffs-from-previous-editions.md

In the relationship table, there should be strikethrough text for removed relationships.

But it is displayed as:
```
~~DEPENDENCY_OF~~
```
instead of
~~DEPENDENCY_OF~~

### PR DESCRIPTION
**Pull request by bact**
Python Markdown that mkdocs use doesn't support the rendering of `~~text~~` to ~~text~~ (strikethrough). Need to call an extension to support that.

- Adding [pymdownx.tilde](https://facelessuser.github.io/pymdown-extensions/extensions/tilde/) extension to mkdocs.yml config
- Adding [pymdown-extensions](https://pypi.org/project/pymdown-extensions/) module to requirements.txt dependencies

This will fix #929

Before fix:
Screenshot 2024-07-23 at 00 54 34

After fix:
Screenshot 2024-07-23 at 00 53 36

### CODE REVIEW

**Comment by zvr** [comment]
I don't think we should have strikeout support. I'm not sure it's allowed in standards.

**Comment by goneall** [comment]
> I don't think we should have strikeout support. I'm not sure it's allowed in standards.

Is there some other annotation we can use for the changes where a relationship is removed?  I know it is in the text, but it is much more readable with the strikethrough.

**Comment by bact** [comment]
I skimmed through few OMG documents and see that they use different fonts, different sizes, character colors, background colors, underline, bold, and italic.

But that's not definitive. Wonder if there's a style guide or a list of allowed typographic devices for OMG/ISO standards?

**Comment by bact** [comment]
For the diff between versions, this spec use just "blank" cells for deletion.
https://www.omg.org/spec/MOF/2.5.1/PDF
Screenshot 2024-07-24 at 10 08 03

**Comment by goneall** [comment]
Discussed on 30 July 2024 tech call, we'll open a new PR to remove the strikethroughs.  Agreed we didn't need the additional formatting.

Closing this PR.

**Comment by bact** [comment]
Remove the strikethroughs: https://github.com/spdx/spdx-spec/pull/1017

**Pull request closed without merging**
