### PR TITLE
Initial description of "Proposal of Useage Profile for SPDX 3.0"

### PR DESCRIPTION
**Pull request by yoshi-i**
This is the Usage Profile to describe license constraints when it integrated into "the Product".
Proposal made with "License Info. Exchange SWG of Open Chain Project".

Signed-off-by: Yoshiyuki Ito <yoshiyuki.ito.ub@renesas.com>

### CODE REVIEW

**Comment by yoshi-i** [comment]
Thank you for quick response. I've renamed and divided a file to usage-profile.md and licensing-profile_usage-profile.md
The file 'licensing-profile_usage-profile.md' is made from the portion "License Constraint and Licensing Compatibility" of usage-profile to be further discussions.

And I will discuss about "thought experiments of relationships to PREREQUISITE" with peoples correspond to this proposal.

**Comment by jlovejoy** [comment]
I have not had a chance to read all of this, but the license compatibility aspect is untenable:
SPDX does not make legal interpretations. License compatibility requires: a legal interpretation (over which, not all lawyers will agree), involves the interpretation of the license text themselves, as well as how the software is being used or interacts. This is all outside the scope of SPDX.

**Comment by yoshi-i** [comment]
Thank you for comments, I'm considering how I explain background of this pull request.
And I understood I must obey section 1.4(What does this specification cover?) and 1.5(What is not covered in the specification?) to propose new profile.

> SPDX does not make legal interpretations.

Also I've pointed out issues on the meeting from Kate-san and Steve-san, so I will apply update to my proposal to be covered as in section 1.4.

**Comment by tsteenbe** [comment]
As discussed in the OpenChain Automotive Workgroup call on August 19th, I working on transforming this proposal into something that's compatible with SPDX design principles.  

Discussed the requirements that came up in the call within the SPDX tech call of August 25th, see https://wiki.spdx.org/view/Technical_Team/Minutes/2020-08-25

**Comment by yoshi-i** [comment]
To brush up my proposal, I'm considering where is it the place of each elements of Usage Profile into current SPDX structure as following files.

[UsageProfile_On_SPDX_Structure.png](https://github.com/OpenChain-Project/Japan-WG-General/blob/master/License-Info-Exchange/Proposal/UsageProfile_On_SPDX_Structure.png)

**Pull request closed without merging**
