### PR TITLE
Update References chapter

### PR DESCRIPTION
**Pull request by bact**
- Add Non-normative References section
- Using text from Bob's Word doc 2024-07-22 and existing reference formatting from `normative-reference.md`:
- Links update
  - "The Minimum Elements For a Software Bill of Materials"
    - https://www.ntia.doc.gov/files/ntia/publications/sbom_minimum_elements_report.pdf not found
    - update to https://www.ntia.gov/report/2021/minimum-elements-software-bill-materials-sbom
  - NIST IR 7695
    - https://csrc.nist.gov/publications/detail/nistir/7695/final -> https://csrc.nist.gov/pubs/ir/7695/final

### Notes
- https://spdx.org/rdf/ontology/spdx-3-0-1 does not exist
- List formatting consistency
  - Normative References uses regular paragraphs, one reference per one paragraph - no numbered
  - Non-normative References uses numbered list
    - Because these numbers will be used in "Annex F: History, Motivation and Rational" (in the text as `[6]`, `[2, 3]`, etc)
- Numbering 10, 11, 12 in this PR and in the Word doc is not sync. As in the original Word doc `10.` is missing/skipped.
  - Need to resync the numbers with the final Annex F.
- For IETF RFC links, wait for a decision from https://github.com/spdx/spdx-spec/issues/1012

### CODE REVIEW

**Comment by bact** [comment]
Missing refs? These are referred to in [ExternalIdentifierType](https://spdx.github.io/spdx-spec/v3.0/model/Core/Vocabularies/ExternalIdentifierType/) but not yet documented in References:

- https://csrc.nist.gov/glossary/term/cve_id - for `cve`
- https://datatracker.ietf.org/doc/html/rfc3696#section-3 - for `email`
- https://www.ietf.org/archive/id/draft-ietf-sacm-coswid-21.html#section-2.3 - for `swid`
- https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml - for `urlScheme`

**Comment by bact** [comment]
Should we specify the version for "Common Platform Enumeration (CPE) – Specification" ?

- There's no version specified for "Common Platform Enumeration (CPE) – Specification" in the Normative References section.
  - Its URL in the our document is https://cpe.mitre.org/files/cpe-specification_2.2.pdf
- At the top of our Normative References section, we said
    `"For undated references, the latest edition of the referenced document (including any amendments) applies."`
  - The latest and last version (before it was archived) of CPE is 2.3, see: https://cpe.mitre.org/specification/
  - Does this means, for this ref, CPE 2.3 will apply?
- Next to it, we we also have a ref to "NIST IR 7695 Common Platform Enumeration: Naming Specification Version 2.3" which is part of CPE 2.3 stacks.
- In our current v3 model, there are at least two citations to CPE, in [ExternalIdentifierType](https://spdx.github.io/spdx-spec/v3.0/model/Core/Vocabularies/ExternalIdentifierType/):
  - `cpe22` cites https://cpe.mitre.org/files/cpe-specification_2.2.pdf
  - `cpe23` cites NIST IR 7695


Should we change the line:
"Common Platform Enumeration (CPE) – Specification, The MITRE Corporation"
to:
"Common Platform Enumeration (CPE) – Specification 2.2, The MITRE Corporation" ?

--

https://github.com/spdx/spdx-3-model/pull/806 will clarify this on the model side.

**Review by bobmartin3000 — APPROVED** [review]
LGTM

**Review by kestewart — APPROVED** [review]
Looks good.

**Review by goneall — APPROVED** [review]
LGTM

**Pull request merged**
