### PR TITLE
Add Copyrights and licensing page

### PR DESCRIPTION
**Pull request by bact**
Add new copyrights info to index.md
- <s>Using text from Bob's Word doc 2024-07-22</s>
- Using text from https://github.com/spdx/spdx-spec/pull/1010#issuecomment-2276868453

### CODE REVIEW

**Review by bobmartin3000 — APPROVED** [review]
LGTM

**Review by swinslow — CHANGES_REQUESTED** [review]
Please hold on merging this, I'm reviewing and discussing with the SC.

**Comment by swinslow** [comment]
@bact Can we revise this as follows?

* Rather than the four copyright notices at the top, please replace with: "Copyright © 2010-2024, Linux Foundation and its Contributors, including SPDX Model contributions from OMG and its Contributors"
* Following that, keep the references to the licenses that you've included (I'll defer to you and the team on whether those should reference Annex G and H, or not; I'm not sure how the new spec document is being structured)
* Following that, please re-insert the "With thanks to..." list of individuals from https://spdx.github.io/spdx-spec/v3.0/ (and any additions, if there are any new individuals to be added for 3.0.1)

**Comment by bact** [comment]
> @bact Can we revise this as follows?
> 
>     * Rather than the four copyright notices at the top, please replace with: "Copyright © 2010-2024, Linux Foundation and its Contributors, including SPDX Model contributions from OMG and its Contributors"
> 
>     * Following that, keep the references to the licenses that you've included (I'll defer to you and the team on whether those should reference Annex G and H, or not; I'm not sure how the new spec document is being structured)
> 
>     * Following that, please re-insert the "With thanks to..." list of individuals from https://spdx.github.io/spdx-spec/v3.0/ (and any additions, if there are any new individuals to be added for 3.0.1)

@swinslow Done. Everything is now in index.md.

**Comment by kestewart** [comment]
Pending discussion between Bob, Steve & Mike.

**Comment by swinslow** [comment]
Hi @bact,

On the linking to the license texts in GitHub, I don't have a particular preference here. Especially if it means having to keep track of version / branch numbers as the spec evolves, I'm fine with just the general reference since they're included as annexes in the spec anyway.

As @kestewart mentioned, we had a few further edits based on discussions with OMG. Would you mind making a couple further update? Thank you again for all your help!

= = = = =

1. On a new line immediately prior to "This work is licensed under the...", please add a heading that says "Use of Specification - Terms, Conditions & Notices"

2. After that paragraph, please add the following text:

```
Trademarks 

SPDX® is a registered trademark of the Linux Foundation. 

Compliance

Use of the SPDX trademarks is subject to the SPDX Trademark License, currently available at https://spdx.dev/about/legal-notices/

Software developed under the terms of the licenses under which this specification is issued may claim compliance or conformance with this specification if and only if the software provider complies with the SPDX Trademark License given above.
```

= = = = =

@bobmartin3000 @kestewart I'm suggesting that for the SPDX published version of the spec, we retain the "With thanks to..." section where it is. I understand that OMG may shift that to a different clause for their version. 

Please take a look and let me know if you have concerns about either of the changes above. Thanks!

**Comment by bact** [comment]
@swinslow added the new section as you suggested. 

I also added another heading "Contributors" so the list of contributors is separated from the "Use of Specification"  If you think it may be not a good idea, please tell. thx

**Comment by bobmartin3000** [comment]
LGTM - thanks Steve.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Steve Winslow ***@***.***>
Sent: Friday, August 9, 2024 3:52:10 PM
To: spdx/spdx-spec ***@***.***>
Cc: Robert A Martin ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [spdx/spdx-spec] Add Copyrights and licensing page (PR #1010)

Hi @bact, On the linking to the license texts in GitHub, I don't have a particular preference here. Especially if it means having to keep track of version / branch numbers as the spec evolves, I'm fine with just the general reference since


Hi @bact<https://github.com/bact>,

On the linking to the license texts in GitHub, I don't have a particular preference here. Especially if it means having to keep track of version / branch numbers as the spec evolves, I'm fine with just the general reference since they're included as annexes in the spec anyway.

As @kestewart<https://github.com/kestewart> mentioned, we had a few further edits based on discussions with OMG. Would you mind making a couple further update? Thank you again for all your help!

= = = = =

  1.  On a new line immediately prior to "This work is licensed under the...", please add a heading that says "Use of Specification - Terms, Conditions & Notices"

  2.  After that paragraph, please add the following text:

Trademarks

SPDX® is a registered trademark of the Linux Foundation.

Compliance

Use of the SPDX trademarks is subject to the SPDX Trademark License, currently available at https://spdx.dev/about/legal-notices/

Software developed under the terms of the licenses under which this specification is issued may claim compliance or conformance with this specification if and only if the software provider complies with the SPDX Trademark License given above.


= = = = =

@bobmartin3000<https://github.com/bobmartin3000> @kestewart<https://github.com/kestewart> I'm suggesting that for the SPDX published version of the spec, we retain the "With thanks to..." section where it is. I understand that OMG may shift that to a different clause for their version.

Please take a look and let me know if you have concerns about either of the changes above. Thanks!

**Comment by bact** [comment]
@swinslow @bobmartin3000 @kestewart how are we supposed to use the name "Linux Foundation"?

- Without "the"
  - `Copyright © 2010-2024, Linux Foundation` 
  - As suggested in the first bullet of https://github.com/spdx/spdx-spec/pull/1010#issuecomment-2276868453
- With "the"
  - `SPDX® is a registered trademark of the Linux Foundation.`  
  - Only uppercase the first letter, if it is the first word in the sentence
  - As suggested in Trademark section here https://github.com/spdx/spdx-spec/pull/1010#issuecomment-2278642863
- With "The"
  - `This document was prepared by The Linux Foundation`
  - Always uppercase the first letter
  - As suggested in the ISO Foreword discussion https://github.com/spdx/spdx-spec/pull/1001#discussion_r1712073965

**Comment by swinslow** [comment]
@bact Good eye.  :)  The formal name of the LF is "The Linux Foundation". So for each of those, it should be a first-letter-capitalized "The" at front. Thanks for catching this!

**Comment by bact** [comment]
Thank you, I will change that accordingly.

**Comment by swinslow** [comment]
@bact One comment from your changes -- let's please not use the word "Contributors" for the heading there. That's because that word has particular meanings under the Community Spec license and I just want to avoid confusion around that (this relates also to the discussions we had with OMG yesterday).

Agreed though with setting it off separately from the rest. Perhaps just "Thanks" as the heading?

**Comment by bact** [comment]
@swinslow got it. Will change the heading too

**Comment by bact** [comment]
@swinslow done.

**Comment by swinslow** [comment]
Sorry @bact, I just realized one more tweak -- my apologies  :)

The heading "## Use of Specification - Terms, Conditions & Notices" on line 15 -- that should appear _above_ "This work is licensed under..." on line 6. After that change, I think we can call this done!

**Review by swinslow — APPROVED** [review]
Thank you for handling all the adjustments, @bact. Greatly appreciate it!

**Comment by bact** [comment]
@swinslow thank you for super quick review as well

**Review by kestewart — APPROVED** [review]

**Pull request merged**
