### PR TITLE
Change Package Purpose to Primary Package Purpose

### LINKED ISSUE #720: Should packagePurpose have cardinality 0..1?
[Package Purpose](https://github.com/spdx/spdx-spec/blob/development/v2.3/chapters/package-information.md#724-package-purpose-field-) currently has a cardinality of `0..*` allowing more than one purpose.

@rjb4standards raised a good [issue in the schema pull request](https://github.com/spdx/spdx-spec/pull/716#pullrequestreview-1007709766):

> I'm concerned that making PackagePurpose an array will impact fidelity when translating to other formats, plus it raises ambiguity as to the "primary purpose" of a package.

Should we change the cardinality to `0..1` to resolve this issue?

### PR DESCRIPTION
**Pull request by goneall**
Fixes #720

Signed-off-by: Gary O'Neall <gary@sourceauditor.com>

### CODE REVIEW

**Comment by goneall** [comment]
@nishakm  - let me know if this looks good to you - see issue #720 for context.

**Comment by rjb4standards** [comment]
REA supports this proposed change to use Primary Package Purpose with a cardinality of 0..1, with content constrained to one of the enumerated set of valid options specified for SPDX Version 2.3.

**Review by nishakm — APPROVED** [review]

**Comment by rnjudge** [comment]
@goneall what would this field be called in the JSON format? `primaryPackagePurpose`? or just `primaryPurpose`?

**Comment by goneall** [comment]
> what would this field be called in the JSON format? primaryPackagePurpose? or just primaryPurpose?

@rnjudge `primaryPackagePurpose` - consistent with the RDF property name.

**Pull request merged**
