### PR TITLE
meeting.ics: Document general, outreach, legal, and technical meetings

### PR DESCRIPTION
**Pull request by wking**
The current wiki wording for these meetings [makes it sound like they're pinned to UTC][1], when in fact they are intended to [float with US Pacific Time (`America/Los_Angeles`)][2].  Having a machine-redable format makes it possible for everyone's calendar software to handle those time conversions for them (and allows non-US-DST participants to avoid internalizing the US DST rules).

I'm not sure the outreach group still exists.  The [wiki page][3] doesn't say anything about the group disolving, but [the minutes end on 2014-04-24][4].

The distinction in UberConference channels seems intentional, with Kate's channel [allowing more participants][5].

Future bumps to `meeting.ics` should bump [`LAST-MODIFIED`][6] or [`DTSTAMP`][7] for any altered components.  We can't use `LAST-MODIFIED` in the `VEVENT` because [`VEVENT`s require `DTSTAMP`][8].

The timezone entry is based on [this `America/New_York` example][9].

The duplicated `DESCRIPTION` and `LOCATION` URLs are less DRY, but makes life easier for folks pulling up the calendar a minute before the meeting, since they don't have to click through to the wiki pages.  The [`LOCATION`][10] entry seems like a reasonable location for the conference-call page, so I've used that.  Note that the URI there is a text value; [`LOCATION` supports URIs in `ALTREP`][10], but the UberConference page isn't an “[alternate text representation for the property value][11]”.  The URI in `DESCRIPTION` is a fallback for clients that don't support/display `LOCATION` (I'm not sure if any exist, but it's easy to play it safe).  I couldn't find a more structured location for the phone number, unless we also wanted to put that in `LOCATION`.

com.android.calendar version 7.1.1 only displays the `DESCRIPTION` body, and does not provide a link to `ALTREP` (in fact, I don't see any instances of `ALTREP` in [the source][12]).  Including the wiki link in the `DESCRIPTION` body gives folks using that calendar application an easy way to get to the wiki pages.

The ICS was validated [here][13].

The CRLF line endings are [intentional][14], and the `.gitattributes` entry ensures we keep them.  The committed files will still have LF endings, which can confuse `git diff …`, but you can use `--ignore-space-at-eol` to see what really changed.

[1]: https://lists.spdx.org/pipermail/spdx-legal/2017-September/002239.html
[2]: https://lists.spdx.org/pipermail/spdx-legal/2017-September/002240.html
[3]: https://wiki.spdx.org/view/Outreach_Team
[4]: https://wiki.spdx.org/view/Business_Team/Minutes
[5]: https://lists.spdx.org/pipermail/spdx-legal/2017-September/002236.html
[6]: https://tools.ietf.org/html/rfc5545#section-3.8.7.3
[7]: https://tools.ietf.org/html/rfc5545#section-3.8.7.2
[8]: https://tools.ietf.org/html/rfc5545#section-3.6.1
[9]: https://tools.ietf.org/html/rfc5545#page-69
[10]: https://tools.ietf.org/html/rfc5545#section-3.8.1.7
[11]: https://tools.ietf.org/html/rfc5545#section-3.2.1
[12]: https://android.googlesource.com/platform/packages/apps/Calendar/+/android-7.1.1_r38
[13]: https://icalendar.org/validator.html
[14]: https://tools.ietf.org/html/rfc5545#section-3.1

### CODE REVIEW

**Comment by zvr** [comment]
They have to be different calendar files for the different meetings, since most people want to attend (and therefore import) only one.

**Comment by wking** [comment]
> There have to be different calendar files for the different meetings, since most people want to attend (and therefore import) only one.

Hmm. I'd expect most people want to atted general meetings, and then at least one more-specific team meeting.  But I'm not clear that we need seperate files for that.  This file is for when the SPDX meetings are, not for when you're attending.  You can mark your attendance locally for each event as you see fit.  And if you'll never be intetested in the legal meetings (for example), at least Google Calender gives you the option of deleting events from imported `.ics`.

That said, splitting into per-meeting files is certainly possible, if folks really want to go that way.

**Comment by wking** [comment]
I've pushed ed7a336 → a84ccc8 to [drop the 2017-10-24 tech meeting][1].

[1]: https://lists.spdx.org/pipermail/spdx-tech/2017-October/003440.html

**Comment by wking** [comment]
I've pushed a84ccc8 → 2aeebc9 to [drop the 2017-10-26 legal meeting][1].

[1]: https://lists.spdx.org/pipermail/spdx-legal/2017-October/002305.html

**Comment by pombredanne** [comment]
You make good points, but I am not sure it make sense to mix things up: the meeting times and the spec are not really related, are they?
Should you close this?

**Comment by wking** [comment]
On Tue, Nov 14, 2017 at 08:38:23AM +0000, Philippe Ombredanne wrote:
> … the meeting times and the spec are not really related, are they?
> Should you close this?

I'm fine putting this somewhere else [1].  Where would you like it
instead?

[1]: https://lists.spdx.org/pipermail/spdx-legal/2017-September/002244.html

**Comment by pombredanne** [comment]
On the SPDX.org web page?

**Comment by wking** [comment]
> On the SPDX.org web page?

Is there a repository for that?  It seems like it would be tedious for the web admins to maintain the file if they had to field emails and such for every update.  Much easier to review changes and merge/deploy with a Git repository.

Coverting spdx.org to a static site (Jekyll, Hugo, etc.) built from a public Git repo would be awesome (third parties could supply patches for [things like this][1], where they can currently only file issues.  But a conversion like that would be a big lift.  Maybe we can convert incrementally, with Nginx (which seems to be involved in serving spdx.org) using [`try_files`][2] to serve a static file for pages that had been converted, falling back to the current engine for pages that hadn't?

I'm happy to help with any of that, and I'm ha[py to mock things up if folks want something concrete to experiment with.  But for this PR, I just want the `.ics` landed somewhere that shows it has been reviewed and approved by SPDX maintainers.  If the way to do that is to mail it to the webmaster, or file a Bugzilla bug, or whatever, let me know.

[1]: https://bugs.linuxfoundation.org/show_bug.cgi?id=1390
[2]: http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files

**Comment by pombredanne** [comment]
On Wed, Nov 15, 2017 at 3:55 PM, W. Trevor King <notifications@github.com>
wrote:

> On the SPDX.org web page?
>
> Is there a repository for that? It seems like it would be tedious for the
> web admins to maintain the file if they had to field emails and such for
> every update. Much easier to review changes and merge/deploy with a Git
> repository.
>
> Coverting spdx.org to a static site (Jekyll, Hugo, etc.) built from a
> public Git repo would be awesome (third parties could supply patches for things
> like this <https://bugs.linuxfoundation.org/show_bug.cgi?id=1390>, where
> they can currently only file issues. But a conversion like that would be a
> big lift. Maybe we can convert incrementally, with Nginx (which seems to be
> involved in serving spdx.org) using try_files
> <http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files> to
> serve a static file for pages that had been converted, falling back to the
> current engine for pages that hadn't?
>
> I'm happy to help with any of that, and I'm ha[py to mock things up if
> folks want something concrete to experiment with. But for this PR, I just
> want the .ics landed somewhere that shows it has been reviewed and
> approved by SPDX maintainers. If the way to do that is to mail it to the
> webmaster, or file a Bugzilla bug, or whatever, let me know.
>

The new dial in numbers and times are sent to the mailing list as .ics ...
tracking the latest on the web page is plenty good enough

**Comment by wking** [comment]
> The new dial in numbers and times are sent to the mailing list as .ics ... tracking the latest on the web page is plenty good enough

Well, I'll need to know where it will be posted to fill in the `URL` field, although the webmaster can fill those in on posting.  The benefits of a stable URL are:

* You have a known-current place to link from the wiki pages, and
* Calendar software can poll and pull in updates automatically.

**Comment by wking** [comment]
I've pushed 2aeebc9 → bb7ee2c to pick up the new phone numbers, UberConference URLs, and legal 2017-11-21 meeting.

**Comment by goneall** [comment]
> Is there a repository for that? It seems like it would be tedious for the web admins to maintain the file if they had to field emails and such for every update. Much easier to review changes and merge/deploy with a Git repository.

On Thursday, 16 Nov the outreach team meeting will include the website designers.  It looks like the Linux Foundation is moving to wordpress, so there may be an opportunity to automate this in some way.

@jmanbeck - can we add the calendar maintenance to the discussion?

**Comment by wking** [comment]
Ah, [1] is possibly a better example of a static project site in the
LF context ;).

[1]: https://www.kernel.org/doc/html/latest/

**Comment by wking** [comment]
On Wed, Nov 15, 2017 at 05:44:53PM +0000, goneall wrote:
> On Thursday, 16 Nov the outreach team meeting will include the
> website designers.

Ah, nice, I wasn't sure if they were still meeting.  Do you know of
any minutes for them that are more recent than 2014 [1]?

> It looks like the Linux Foundation is moving to wordpress, so there
> may be an opportunity to automate this in some way.

I don't know why a mostly-volunteer project would prefer a dynamic
site.  It seems like lowering the bar to third-party contributions
(for both submission and acceptance) with a static site (e.g. [2])
would help reduce the maintenance burden.  Going with WordPress
instead gives you… a pretty editing UI?  Warmer servers?  ;)

But I'm fine with whatever the webmasters want, as long as I can
figure out what that is :).

[1]: https://wiki.spdx.org/view/Business_Team/Minutes
[2]: https://github.com/swcarpentry/website

**Comment by goneall** [comment]
> Ah, nice, I wasn't sure if they were still meeting.  Do you know of
any minutes for them that are more recent than 2014 [1]?

Still meeting and providing results in organizing outreach and maintaining the website - although not as active as the tech and legal teams.  @jmanbeck - do you have a pointer to minutes?

**Comment by jmanbeck** [comment]
I guess so. Not sure what youre looking for. But if there is time yes.

Jack

**Comment by wking** [comment]
On Wed, Nov 15, 2017 at 06:38:15PM +0000, jmanbeck wrote:
> Not sure what youre looking for.

a. Is there interest in hosting a canonical *.ics like the one I've
   worked up here in an official SPDX location?  If so:

   b. What location?  A file in this repo?  Another repo?  Under
      https://spdx.org?  I'd like a URL for the reasons given in [1].

   c. How should updates to the canonical *.ics be submitted?  Will
      submissions be public?  Who will review them?  Who gets to
      decide which updates are accepted?  Who publishes accepted
      updates (if different from the accept-or)?

d. Do you want help making any of that happen?  If so, how can I
   contribute?

[1]: https://github.com/spdx/spdx-spec/pull/42#issuecomment-344629578

**Comment by wking** [comment]
I wasn't able to make the outreach meeting :/.  Did this issue get discussed there?

**Comment by goneall** [comment]
We briefly discussed the calendaring.  There is a calendar plugin for wordpress which allows .ics files to download and also renders and HTML calendar with all of the events.

Action is to look into the plugin to see if it may be part of the solution.  We would need to upload updates to the calendar which would not be as convenient as github, but it may be more convenient to the users downloading the updates.

Link to the plugin:  https://theeventscalendar.com/product/wordpress-events-calendar/

**Comment by wking** [comment]
On Thu, Nov 16, 2017 at 11:56:53PM +0000, goneall wrote:
> We would need to upload updates to the calendar which would not be
> as convenient as github…

Would GitHub still be the recommended channel for submitting updates?
Or is it mail to spdx@?  Somewhere else?  Or is this going to be
maintained internally with no channel for submitting updates?

> … but it may be more convenient to the users downloading the
> updates.

As long as there's a download URL for the *.ics, I don't see a big
difference in download convenience.

Rendering the calendar to HTML is nice for folks who aren't
downloading the *.ics though.  Maybe that's what you are thinking of?

> Link to the plugin:
> https://theeventscalendar.com/product/wordpress-events-calendar/

I'm not familiar with the WordPress ecosystem, let alone this
particular plugin.  But going to their demo [1], clicking “Export
Events” [2], and dumping the resulting *.ics into [3] turns up ten
line-length warnings like:

  Line length should not be longer than 75 characters near line # 17
  Reference: RFC 5545 3.1. Content Lines

and 76 TZID errors:

  Invalid TZID value (America/Los_Angeles) near line # 9
  Reference: 3.2.19. Time Zone Identifier

it looks like their iCalendar formatter has poor wrapping and fails to
include timezone definitions [4].

As an alternative, you can use Google (or probably any number of
tools) to embed a rendering of an imported *.ics file.  For example,
here's Google rendering an import of the *.ics from my branch [5].

[1]: http://wpshindig.com/events/
[2]: http://wpshindig.com/events/?ical=1&tribe_display=month
[3]: https://icalendar.org/validator.html
[4]: https://github.com/wking/spdx-spec/blob/0fad86fcc606f66f81d89930f616cf53f5ade35e/meeting.ics#L4-L21
[5]: https://calendar.google.com/calendar/embed?src=ahbk0skikkmbg4ns36mrp0ei5skhlt82%40import.calendar.google.com&ctz=America/Los_Angeles

**Comment by goneall** [comment]
> Would GitHub still be the recommended channel for submitting updates?
Or is it mail to spdx@?  Somewhere else?  Or is this going to be
maintained internally with no channel for submitting updates?

Not clear at this point, most likely maintained internally which would be a disadvantage relative to git

>As long as there's a download URL for the *.ics, I don't see a big
difference in download convenience.

> Rendering the calendar to HTML is nice for folks who aren't
downloading the *.ics though.  Maybe that's what you are thinking of?

Yes  - that is what we were thinking of

> As an alternative, you can use Google (or probably any number of
tools) to embed a rendering of an imported *.ics file.  For example,
here's Google rendering an import of the *.ics from my branch [5].

@wking you've pointed out some deficiencies in the plugin - we could also just stay with the git and Wiki solutions as well

**Comment by wking** [comment]
I've added an [event for the LF Leadership Summit][1] with 0fad86f → 0fc92df.

[1]: https://lists.spdx.org/pipermail/spdx/2017-November/001152.html

**Comment by wking** [comment]
I've [dropped the 2018-02-06 tech meeting][1] with bce5990 → 3df187e.

[1]: https://lists.spdx.org/pipermail/spdx-tech/2018-February/003533.html

**Comment by kestewart** [comment]
Mail system is moved so this is stale.   Closing this.

**Pull request closed without merging**
