### PR TITLE
ISO-required: Correct and change headings to sentence case

### PR DESCRIPTION
**Pull request by RexJaeschke**

### CODE REVIEW

**Comment by goneall** [comment]
@RexJaeschke Can you sign-off your PR's - see https://github.com/spdx/spdx-spec/pull/575/checks?check_run_id=3690923081 for more information.

**Comment by goneall** [comment]
@RexJaeschke If you could sign these off - it would also be nice to "squash" these commits to a single commit.

**Review by goneall — APPROVED** [review]

**Comment by goneall** [comment]
@RexJaeschke Can you take a look at these changes and confirm this matches the ISO document - When I looked at the diffs document you sent on Sept. 14, these changes were not highlighted in the document

**Comment by RexJaeschke** [comment]
@goneall The first 3 changes (D.4.2, .3, and .4) are *not* in the ISO spec, but all the others are. Based on ISO's rules, those 3 should be as I changed them. If you decide to remove those 3 changes, it would be good to leave a note somewhere to change them next time (perhaps as an HTML comment at that top of that file).

**Comment by goneall** [comment]
@RexJaeschke Thanks for the explanation - I'll go ahead and merge

**Pull request merged**
