### PR TITLE
Fix nondisplayable characaters

### PR DESCRIPTION
**Pull request by vargenau**
Replace characters that cannot be displayed by quotation marks and Copyright symbol in file SPDXTagExample-v2.2.spdx.

Signed-off-by: Marc-Etienne Vargenau <marc-etienne.vargenau@nokia.com>

### CODE REVIEW

**Review by goneall — APPROVED** [review]
Thanks @vargenau

**Comment by goneall** [comment]
I'm wondering if this same issue is in the other formats (e.g. JSON).  I haven't had a chance to look - but if it is, we can either edit directly or run the converter on the corrected tag/value file.

**Review by kestewart — APPROVED** [review]

**Comment by vargenau** [comment]
> I'm wondering if this same issue is in the other formats (e.g. JSON). I haven't had a chance to look - but if it is, we can either edit directly or run the converter on the corrected tag/value file.

I have updated the other formats.

**Review by goneall — APPROVED** [review]
Thanks @vargenau - I double checked the encoding and all looks good.

**Pull request merged**
