### PR TITLE
Add missing ref, fix list issue, fix nav bar, cleanup Markdown formatting

### PR DESCRIPTION
**Pull request by bact**
Update 2024-07-11, this PR will be closed as some docs are moved to spdx/using repo.

- docs/annexes/diffs-from-previous-editions.md -- now in new PR #988
- docs/annexes/getting-started.md -- now in spdx/using repo
  - Add missing ref of `[Property_externalIdentifierType]` -- already fixed by other PR
- docs/annexes/using-SPDX-to-comply-with-industry-guidance.md -- now in spdx/using repo
  - Remove extra space at the end of `[Core/Classes/Artifact.suppliedBy ]` -- will fix in spdx/using repo
- Cleanup Markdown formatting
  - Apart from keeping consistency, this is also to avoid any possible rendering issue due to Markdown-flavour incompatibility between GitHub and mkdocs.
  - Fix list issue in Serialization chapter -- now in new PR #990
  - Fix list issue in [Annex F - F.2](https://spdx.github.io/spdx-spec/v3.0/annexes/using-SPDX-to-comply-with-industry-guidance/) -- in new PR https://github.com/spdx/using/pull/2
  - See more details in a similar fix at SPDX v3 Model: https://github.com/spdx/spdx-3-model/pull/723

### CODE REVIEW

**Comment by bact** [comment]
The list issue (list rendering incorrectly if there's no blank line before the list) is a known issue since 2.3.1, see #825

**Review by goneall — APPROVED** [review]
LGTM - Thanks @bact

**Comment by bact** [comment]
Additional fix - Use H2 for top headings in `docs/annexes/diffs-from-previous-editions.md` so mkdocs's readthedocs theme can generate proper navigation (H1 is reserved for a title in Markdown).

Since the navigation in current v3.0 is somewhat already broken, it is hard to see. Better check its cousin in v2.3 doc at https://spdx.github.io/spdx-spec/v2.3/diffs-from-previous-editions/ to see it more clearly. (both of them share the same Markdown structure, and mistakes).

You can see that in v2.3, for other Annexes when you clicked on the Annex title on the navigation bar, headings will be expanded in the nav bar. But for `Annex I Differences from Earlier SPDX Versions`, it didn't. This because of the use of H1 as headings.

**Comment by bact** [comment]
Will close this PR as some of the docs here are already transferred to `spdx/using` repo (https://github.com/spdx/using/pull/1), will continue to fix there instead.

Some other fixes will be open as new PRs.

**Pull request closed without merging**
