### PR TITLE
Rework this section for better flow

### PR DESCRIPTION
**Pull request by kestewart**
Add in missing sections,  update diagram,  make cardinality explicit for all sections.

### CODE REVIEW

**Comment by RexJaeschke** [comment]
Looks good to me.

**Comment by swinslow** [comment]
On the Packages description though, just to mention -- I realize this is a short summary, but I do want to make sure we preserve somewhere the [longer description of Packages](https://spdx.github.io/spdx-spec/1-rationale/#16-what-does-package-mean-in-the-context-of-spdx) that we worked through last year.

I gathered that the "Rationale" part of the spec might be changing so I just wanted to mention that we should make sure at least that that description is retained, as there was a lot of input from various folks on how best to define "Packages" for purposes of the spec.  Thanks  :)

**Comment by RexJaeschke** [comment]
The Rational chapter is no longer part of the spec. See Issue #254 , which states <<A short definition of "package" goes in "Terms and definitions." The body of the text goes into the new clause, "Composition of an SPDX document." DONE>> [The intent was to redistribute that content into other clauses, one of which was new.] However, I don't see that the bulk of that was in fact moved to the new clause. Yet is sounds like it should be. If so, do you have any suggestion as to where it should be inserted into composition-of-an-SPDX-document.md?

**Comment by swinslow** [comment]
Thanks @RexJaeschke -- apologies, I had missed that issue discussion previously. I think `5.2.2 Package information section` is probably the right place for that content to go, probably just prior to the Cardinality line in that section.

**Pull request merged**
