### PR TITLE
fix: fix typo (definined to defined)

### PR DESCRIPTION
**Pull request by ninoseki**
Hello, thank you for creating & maintaining the standard!

I just noticed a typo in the JSON schema. (`definined`)
So let me create a PR to fix that.

### CODE REVIEW

**Review by seabass-labrax — APPROVED** [review]

**Comment by seabass-labrax** [comment]
Welcome to SPDX, and thank you @ninoseki! :smiley:

**Comment by goneall** [comment]
@ninoseki turns out this same typo is in all the examples - would you mind doing a search/replace and update this PR with updated examples with the same fix?

**Comment by ninoseki** [comment]
Sorry I missed them. I addressed them by e10ba8e.

**Review by goneall — APPROVED** [review]
LGTM

**Comment by goneall** [comment]
Thanks @ninoseki

**Pull request merged**
