### PR TITLE
Changed OWL ontology format from RDF/XML to RDF/Turtle

### PR DESCRIPTION
**Pull request by gitpurva**
#496

### CODE REVIEW

**Comment by zvr** [comment]
Why delete the XML example?

The Turtle ontology looks completely machine-generated, with a number of "nodes" with no meaningful names (see lines 328-359).

**Comment by gitpurva** [comment]
> Why delete the XML example?
         As I have made the file of Rdf/ttl example , therefore I deleted the rdf/xml file.

But in the latest commit I have added that xml example file again :)

**Review by goneall — COMMENTED** [review]
Since Turtle is a more readable version of the ontology, I'm OK adding this as another example file.

**Comment by kestewart** [comment]
Moving to 2.3 as we're lacking quorum to resolve this.

**Comment by tsteenbe** [comment]
@kestewart  Tried to rebase this PR to development/v.2.3 but running into issues as contributor named his feature branch the same as an official SPDX one e.g. `development/v2.2.1`

**Comment by goneall** [comment]
@tsteenbe I'll create a new PR to replace this one once we get closer to a final 2.3 draft

**Comment by goneall** [comment]
An RDF/Turtle version is now included i the schema updates for version 2.3 in PR #716   Closing this PR

**Pull request closed without merging**
