### PR TITLE
Lowercase filenames for cleaner URLs

### LINKED ISSUE #1051: Rename filenames to all lowercase for consistency and cleaner URLs
For cleaner URLs, propose to rename these files:
- `SPDX-Lite.md` to `spdx-lite.md`
- `SPDX-license-expressions.md` to `spdx-license-expressions.md`

Other files are already in all-lowercase, including ones with a word which originally an all-uppercase initialism:
- `changes-from-previous-iso.md` (ISO)
- `pkg-url-specification.md` (URL)
- `rdf-model.md` (RDF)

The all-lowercase `spdx` will also match the other `spdx` instances in the full URL of: `https://spdx.github.io/spdx-spec/...`

I'm suggesting we have this before the publication of v3.0.1 website, so the URLs stay the same.

### PR DESCRIPTION
**Pull request by bact**
Note - https://github.com/spdx/spdx-3-model/pull/840 has to be applied first, before this PR.

For cleaner URLs, propose to rename these files:
- `SPDX-Lite.md` to `spdx-lite.md`
- `SPDX-license-expressions.md` to `spdx-license-expressions.md`

Other files are already in all-lowercase, including ones with a word which originally an all-uppercase initialism:
- `changes-from-previous-iso.md` (ISO)
- `pkg-url-specification.md` (URL)
- `rdf-model.md` (RDF)

The all-lowercase `spdx` will also match the other `spdx` instances in the full URL of: `https://spdx.github.io/spdx-spec/...`

I'm suggesting we have this before the publication of v3.0.1 website, so the URLs stay the same. (This is not affect the PDF generation)

Will fix #1051 (follow up of https://github.com/spdx/spdx-spec/pull/1044#discussion_r1713041135 )

### CODE REVIEW

**Comment by bact** [comment]
These two warnings are to be fixed by another PR in spdx-3-model

> WARNING -  Doc file 'model/ExpandedLicensing/ExpandedLicensing.md' contains a link '../../annexes/SPDX-license-expressions.md', but the target 'annexes/SPDX-license-expressions.md' is not found among documentation files.

> WARNING -  Doc file 'model/ExpandedLicensing/Classes/ConjunctiveLicenseSet.md' contains a link '../../../annexes/SPDX-license-expressions.md', but the target 'annexes/SPDX-license-expressions.md' is not found among documentation files.

**Review by goneall — APPROVED** [review]
LGTM

**Review by bobmartin3000 — APPROVED** [review]
LGTM

**Review by kestewart — APPROVED** [review]
Looks good as soon as it's passing the checks.

**Comment by bact** [comment]
Warnings fixed in https://github.com/spdx/spdx-3-model/pull/840

**Review by kestewart — APPROVED** [review]
Have merged https://github.com/spdx/spdx-3-model/pull/840, so trying to get this to sort.

**Comment by bact** [comment]
@kestewart it's validated now

**Comment by goneall** [comment]
https://github.com/spdx/spdx-3-model/pull/840 was merged, so this can / must be merged for validation to pass

**Pull request merged**
