### PR TITLE
mkdocs: Fix file not found warnings

### PR DESCRIPTION
**Pull request by bact**
Fix file not found issues in spec doc generation.

Currently, `mkdocs serve` and `mkdocs build` emit these warnings:

```
WARNING -  A reference to 'model/Software/Properties/isDirectory.md' is included in the 'nav' configuration, which is not
           found in the documentation files.
WARNING -  A reference to 'model/Dataset/Classes/Dataset.md' is included in the 'nav' configuration, which is not found
           in the documentation files.
WARNING -  A reference to 'model/Dataset/Properties/sensitivePersonalInformation.md' is included in the 'nav'
           configuration, which is not found in the documentation files.
WARNING -  A reference to 'model/AI/Properties/sensitivePersonalInformation.md' is included in the 'nav' configuration,
           which is not found in the documentation files.
WARNING -  Doc file 'conformance.md' contains a link 'diffs-from-previous-editions.md', but the target is not found among
           documentation files.
WARNING -  Doc file 'conformance.md' contains a link 'SPDX-Lite.md', but the target is not found among documentation
           files.
```

The first 4 warnings are responsible to the four erroneous `None` class/properties displaying in the left pane of https://spdx.github.io/spdx-spec/v3.0/ . They are all old property names. New property names are already included in the nav. Fixed by removing all 4 outdated references:

- `model/Software/Properties/isDirectory.md` is now `fileKind`
  - https://github.com/spdx/spdx-3-model/pull/666
- `model/Dataset/Classes/Dataset.md` is now `DatasetPackage`
  - https://github.com/spdx/spdx-3-model/pull/671
- `model/Dataset/Properties/sensitivePersonalInformation.md` is now `hasSensitivePersonalInformation`
- `model/AI/Properties/sensitivePersonalInformation.md` is now `useSensitivePersonalInformation`
  - https://github.com/spdx/spdx-3-model/pull/656

The remaining 2 warnings are fixed by add directory name to the targets:

- `diffs-from-previous-editions.md` and `SPDX-Lite.md` are in `annexes/` directory

### CODE REVIEW

**Review by goneall — APPROVED** [review]
LGTM - Thanks @bact

**Review by kestewart — APPROVED** [review]
Thanks for tracking this down and explaining.   LGTM.

**Comment by goneall** [comment]
@bact  - can you resolve the merge conflicts - thanks

**Comment by bact** [comment]
@goneall @kestewart I have tried to resolve the merge conflicts but I cannot see any changes from the development/v3.0.1 branch that will cause the conflict. The bact:fix-file-not-found-warnings branch is basically ahead of the development/v3.0.1 branch without any behind commits.

I opened a new PR #955 and copied the changes from this PR over. If you can re-review it again. Sorry for inconvenience.

**Review by goneall — APPROVED** [review]
LGTM

**Comment by bact** [comment]
Close - merged in #955

**Pull request closed without merging**
