### PR TITLE
Add package-url specification as an annex

### PR DESCRIPTION
**Pull request by zvr**
This adds a (heavily edited) copy of the package-url specification as a new annex.

Signed-off-by: Alexios Zavras <github@zvr.gr>

### CODE REVIEW

**Review by goneall — APPROVED** [review]
Note: There is an ECMA standardization ongoing.  If/when it is standardized, we may need to update this to reconcile any differences between the standards.

**Comment by goneall** [comment]
@kestewart - This was discussed on the tech call and no objections - if you're good with it, please approve / merge

**Review by kestewart — APPROVED** [review]
Addresses a gap.

**Comment by bobmartin3000** [comment]
LGTM

**Pull request merged**
