### PR TITLE
Update publication CI for "develop" branch

### PR DESCRIPTION
**Pull request by bact**
- <s>Use "main" for branch name for the website publication at https://spdx.github.io/spdx-spec/.</s>
  - The update of publication CI for "main" branch will be done separately, as it has to be merged separately into "main" branch
- Use "develop" for branch name for the website publication at https://spdx.github.io/spdx-spec/v3.x.x-dev

According to Tech Team Meeting 2024-11-05:

> Main branch is for keeping released versions

Done by updating `REF_SPEC` variable in `.github/workflows/publish_v3.yml` (Line 25).

### Notes

- This work is one part for #1092
- <s>"main" branch is not exist yet.</s>
  - <s>This PR will not be merged until the branches got renamed.</s>
- `VERSION` is the version to be published when running this workflow.
- `VERSION_DEFAULT` is the default version for redirection if no version is specified in the URL.
-  Currently, our "v3.0.1" is actually "under development" but published to "stable version" URL. This should be only temporary during this transition.
  - After v3.0.1 is officially published and merged to "main", "main" should then be the real stable version and changes in "develop" branch can then be published to https://spdx.github.io/spdx-spec/v3.x.x-dev URL.

#### Publishing "support" branch

- From Tech Team Meeting 2024-11-05:
    > For example, we may be already at 3.2, but we wan to make some changes in 3.0.1.
    > We can have "support" branches (pink line) for that.
    > - "support" branches can live longer (they live until the associated release is deprecated).
- For each "support/x.y." branch (a branch that will have its version published on the website as well under `https://spdx.github.io/spdx-spec/vx.y.z/`):
  - Need to modify `REF_SPEC`, `REF_MODEL`, `VERSION` and  `VERSION_ALIASES` variables in `publish_v3.yml` of that branch.
  - `VERSION_ALIASES` in the "support" branch should not contain "latest"; it is only reserved for "main" branch
  - `VERSION_DEFAULT` should be kept the same across all branches.
    - All non-"main" branches are now prevented from setting the default version (see from Line 180).
    - We may later like to move this VERSION_DEFAULT from the workflow file to a separated text file instead and read the value from that, so we can have a single source of truth.

#### spec-parser version

- This workflow uses the `spec-parser` directly from its "main" branch (see `REF_SPEC`), with an assumption that the "main" spec-parser will work with any version of `spdx-3-model` and with a directory structure in this workflow (in `spdx-spec`).
- To be able, in the future, to specify a version of `spec-parser`, to be use with a particular branch of `spdx-3-model` and of `spdx-spec`, if needed (in case that there are incompatible changes), we may need to have a release branch/tag in `spec-parser` as well.
  - Or alternatively, via the versioning of a Python package (packaging of spec-parser was as proposed in https://github.com/spdx/spec-parser/pull/89 and https://github.com/spdx/spec-parser/pull/104 )

### CODE REVIEW

**Comment by bact** [comment]
Also note that with current branch structure, this workflow will not trigger the check in the PR, as the "on:" in GitHub Actions is now set to "main" and we are not on the "main" yeet. We are still on "development/v3.0.1", so there will be no check yet.

Has to rerun the check once the branch renaming is done.

**Review by goneall — COMMENTED** [review]
From the [branch proposal](https://github.com/spdx/spdx-spec/issues/1092#issuecomment-2457885443), we won't rename the develop/v3.0.1 to main until we tag it for release.

I'll create a PR to document the branch strategy more fully and get some reviews before proceeding.

**Comment by goneall** [comment]
> From the [branch proposal](https://github.com/spdx/spdx-spec/issues/1092#issuecomment-2457885443), we won't rename the develop/v3.0.1 to main until we tag it for release.
> 

@bact 2 questions for you:
- do we need to wait until we release 3.0.1 and merge into main before merging in this PR (since it declares the default as 3.0.1)?
- are you ready for me to do the branch renaming?

**Comment by bact** [comment]
1) Since we don't have https://spdx.github.io/spdx-spec/v3.0.0/ website at the moment, and https://spdx.github.io/spdx-spec/v3.0/ redirects to https://spdx.github.io/spdx-spec/v3.0.1/ the default is already 3.0.1.

    But in terms of keeping the promise that the main should contains only the release one, I think we should wait until we actually release 3.0.1 before merging this PR (this workflow file is not part of the chapters and of the model content, we should have a freedom to adjust it after the release - including updating dependencies in the workflow if needed in the future).

  The "on: push: branches:" trigger in this PR is currently "main", which mean once we merge it any changes in main will be immediately publish.
  The same copy of this file in "develop" branch should triggered by "on: push: branches:" event in "develop" branch.
  
  The top of this file in `main` branch should look like this:
  ```yaml
  on:
  push:
    branches:
      - main
  ```

  The top of this file in `develop` branch should look like this:
  ```yaml
  on:
  push:
    branches:
      - develop
  ```
  
2) I think we are ready.

    But to prevent any unwanted publication during the renaming of branches,
    I will remove (commented out) the trigger section. So the workflow publication will be on a pause.

    Once the renaming is done and checked, we can bring that trigger listening lines back.


@goneall Does it sound a plan?

**Comment by bact** [comment]
(Converted to draft to prevent merging for now.)

**Comment by goneall** [comment]
Thanks @bact - sounds like a plan.

I just renamed all the branches - so we can go ahead with the other PR's.

**Comment by bact** [comment]
There will be this workflow in "main" branch and in "develop" branch.
Each of them publish to a different URL.

For example,
this workflow in "main" can publish to https://spdx.github.io/spdx-spec/3.0.1/,
while this workflow in "develop" can publish to https://spdx.github.io/spdx-spec/3.1-dev/.

The workflow should be configured to have an URL without a version number specified be redirected to an URL published from "main" branch.

**Review by goneall — APPROVED** [review]
LGTM

**Comment by bact** [comment]
@goneall @licquia reviewing this again along with the new branch strategy, I think we may need to document the mapping between the source branch/tag and the target URL more probably. Would you mind to review https://github.com/spdx/spdx-spec/issues/1155 and then we can update this PR please? Thank you

**Comment by bact** [comment]
I have update notes inside the workflow and think we can merge this first for now to allow seeing changes in "develop" branch.

More details about how to handle translation contribution can be adjusted later after we have conclusion from #1155.

After v3.0.1 is merge to "main" branch, we also need a separated PR to update the branch name to "main" at two points in `publish_v3.yml`:
- At `on: push: branches:` trigger
- At `REF_SPEC` environment variable

**Comment by bact** [comment]
Thanks Gary.

**Pull request merged**
