### PR TITLE
Add "Terms and definitions" back to navigation bar

### PR DESCRIPTION
**Pull request by bact**
"Terms and definitions" was previously available, add it back per @bobmartin3000 request (email 2024-08-12/13)

Also removing the "Todo" line from the content.

### CODE REVIEW

**Comment by bact** [comment]
@bobmartin3000  please kindly review.

**Comment by zvr** [comment]
We don't have anything to put in this chapter, why include it?

**Comment by bobmartin3000** [comment]
We have the reference to iso terms and we will need to create specific terms and definitions before the OMG meeting since itbb be is a required section.  With the section there I can say we are working on the terms and definitions.  Without it there we will be told it is required and have to do it any ways.  By putting a placeholder of iso references we show we know we need it.

Bob

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Alexios Zavras (zvr) ***@***.***>
Sent: Tuesday, August 13, 2024 1:51:45 AM
To: spdx/spdx-spec ***@***.***>
Cc: Robert A Martin ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [spdx/spdx-spec] Add "Terms and definitions" back to navigation bar (PR #1064)

We don't have anything to put in this chapter, why include it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <spdx/spdx-spec/pull/1064/c2285389118@ github. com>


We don't have anything to put in this chapter, why include it?

**Review by bobmartin3000 — APPROVED** [review]
LGTM

**Review by kestewart — APPROVED** [review]

**Review by goneall — APPROVED** [review]

**Pull request merged**
