### PR TITLE
Update shacl2code to 0.0.14

### PR DESCRIPTION
**Pull request by bact**
Currently, the example validation [failed for 3.0.1](https://github.com/spdx/spdx-spec/actions/runs/10797439542/job/29948703452?pr=1107).

> _WrappedReferencingError: PointerToNowhere: '/$defs/Artifact' does not exist ...

As discussed during tech call 2024-09-10,
this PR will upgrade shacl2code to fix it.

### CODE REVIEW

**Comment by JPEWdev** [comment]
Release is done. This should be read. Thanks!

**Comment by bact** [comment]
Thank you. All passes for this PR now.

**Review by goneall — APPROVED** [review]
LGTM

**Comment by bact** [comment]
As we already discussed about this on the 10 Sep 2024 tech call and we have two people looking at this already, I will merge this blocking PR.

**Pull request merged**
