### PR TITLE
Finish most remaining cleanup edits

### PR DESCRIPTION
**Pull request by swinslow**
This fixes additional cleanup edits, and nearly (but not quite) completes the list of issues in #454.

Signed-off-by: Steve Winslow <steve@swinslow.net>

### CODE REVIEW

**Comment by swinslow** [comment]
@kestewart I _think_ that this fixes _almost_ all of the issues listed in #454, after it is merged. Can you review and merge if it looks okay?

There are two remaining to address after this is merged, which I've bumped to the top of #454:
* confirm that the sub-bullet points display correctly for the formats list -- I'll check this after the PR is merged and the draft page re-renders
* fix the "differences from v2.1 to v2.2" in Annex J -- I think you said on the call that you would be able to address this? I'm happy to be a second set of eyes afterwards.

Thank you!

**Comment by RexJaeschke** [comment]
Are the formatting changes to "chapters/license-matching-guidelines-and-templates.md" correct? It seems that not all that text should be code.

**Comment by swinslow** [comment]
Thanks @RexJaeschke, good point. I've reverted my edits there and instead made it so that just the `<<var . . .>>` segments themselves get backticks. Feel free to let me know if this still looks incorrect.

**Comment by RexJaeschke** [comment]
@swinslow Looks good now.

**Pull request merged**
