### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by kestewart**
Add missing SPDX-lite contributor.

Signed-off-by: Kate Stewart <kstewart@linuxfoundation.org>

### CODE REVIEW

**Comment by NorioKobota** [comment]
Thanks @kestewart, contributor name is correct.

**Review by goneall — APPROVED** [review]
LGTM

**Comment by goneall** [comment]
@kestewart - We may have some other contributors we missed - we'll add suggestions to this pull request (from the tech call on 16 April)

**Comment by goneall** [comment]
10+ days after initial review, going ahead and merging

**Pull request merged**
