### PR TITLE
New diagrams

### PR DESCRIPTION
**Pull request by zvr**
This updates the diagrams (used in the first Annex) to the latest version generated in the model repo.

### CODE REVIEW

**Comment by goneall** [comment]
From a very cursory review, looks fine.

I'm going to do a more detailed check on the changes since the last diagram update this morning.

**Review by goneall — APPROVED** [review]
LGTM

**Review by bact — APPROVED** [review]
Will update more later on ordering of entries. But this is good for now.

**Comment by bact** [comment]
Validation failed from an known issue and irrelevant to this PR. Will merge

**Pull request merged**
