### PR TITLE
addressed consistency check errors - mainly issue relating to typing

### PR DESCRIPTION
**Pull request by pwin**

### CODE REVIEW

**Review by goneall — APPROVED** [review]
Nice catches - thanks @pwin

**Comment by goneall** [comment]
@pwin - If you could sign-off the commit (e.g. 'git commit --amend --signoff'), I'll go ahead and merge.

**Comment by pwin** [comment]
I think I've done this OK, but if not please let me know

**Comment by goneall** [comment]
@pwin Still showing up as not signed off - see https://github.com/spdx/spdx-spec/pull/483/checks?check_run_id=1291545590

**Comment by pwin** [comment]
please check again, else contact me by email if there is still an issue please

**Pull request merged**
