### PR TITLE
Update terms and definitions

### PR DESCRIPTION
**Pull request by goneall**
Partially resolves issue #253 

Signed-off-by: Gary O'Neall <gary@sourceauditor.com>

### CODE REVIEW

**Comment by goneall** [comment]
Feel free to create pull requests against the updateterms branch if you would like to propose wording changes.

**Comment by swinslow** [comment]
Thanks for this @goneall. I have a few questions for the group -- I'm happy to push a commit to address these, but wanted to get your input first:

* **what does "section" mean?**  It looks like we're potentially using "section" in two different contexts:
  * on its own, to mean a portion of the spec; and
  * together with e.g. "file information," etc., to mean basically a corresponding portion of an SPDX document

It looks to me like we intend for "section" to refer to just the latter point? Or I might be misunderstanding based on the way the definitions are referring to an "instance" of a portion of the spec.

* **"SPDX file" vs. "file information section"**: I gather we're now using "SPDX document" to refer to a complete document -- e.g. .spdx, .spdx.rdf, etc. Within an SPDX document, when we're talking about e.g. the information it contains about a single file, it looks like sometimes we're using "file information section" and sometimes we're using "SPDX file" to mean this. There are similar definitions for both terms. I also see "SPDX package" and "SPDX snippet" used but not define. I lean towards using just "file information section", etc. for these terms, and not defining or using "SPDX file" particularly because of the risk of overlap / confusion.

* **"information" vs. "facts"**: In some of the definitions we refer to sections containing "information", in others we refer to "facts". Unless there's a distinction I'm missing, I'm inclined to use "information" for each of these cases. I think "information" is a bit more general of a term and is probably more accurate than "facts" to refer to sections which can contain comment fields.

There's also a couple of missing line breaks that I can add when pushing a commit to address the things above.

**Comment by RexJaeschke** [comment]
Re "section", ISO calls numbered text document sections "subclauses" while a whole chapter is a "clause."

At one time, Kate had me use the term "fact" for what we know call "section," so if there are occurrences of "fact" still floating around, they should (probably) be changed to "section."

**Comment by goneall** [comment]
re: sections - I am confused about that this means myself.  If someone could replace my definition with a more appropriate definition that would be great.

**Comment by goneall** [comment]
> "SPDX file" vs. "file information section"

I'm OK removing this definition to be consistent now that SPDX document is defined.  @RexJaeschke @kestewart If you're OK with that, I'll update the PR.

**Comment by goneall** [comment]
@swinslow No opinion on the "information" vs "fact".  BTW - feel free to commit directly to the branch or create a PR if you want to update this or any of the other items.

**Comment by goneall** [comment]
@swinslow @kestewart I removed the SPDX file definition.  I'll go ahead and merge this, so any update please create a new PR.

**Pull request merged**
