### PR TITLE
SPDX 3.0 Vulnerability Profile

### PR DESCRIPTION
**Pull request by tsteenbe**
Working progress version of the SPDX 3.0 Vulnerability Profile.

Spec: https://github.com/spdx/spdx-spec/blob/vulnerability-profile/chapters/profile-vulnerabilities.md
Example: https://github.com/spdx/spdx-spec/blob/vulnerability-profile/examples/SPDXVulnerabilityJSONExample-v3.0.spdx.json

If you want to join the discussion surrounding this profile you can join its mailing list at  https://lists.spdx.org/g/spdx-defects.

### CODE REVIEW

**Comment by santosomar** [comment]
A humble suggestion to consider documented in: #511

**Review by santosomar — CHANGES_REQUESTED** [review]
https://github.com/spdx/spdx-spec/pull/510#issuecomment-832228714

**Comment by tsteenbe** [comment]
Closing this PR as it based on old SPDX 3.0 model and this no longer applicable

**Comment by Pivotal-Jeff-Jun** [comment]
@tsteenbe Hi, I noticed that this PR has been closed because it is based on old SPDX 3.0 model/inapplicable.
I was wondering what this `new` model is and how the vulnerabilities will be recorded in 3.0.
And is there any up-to-date examples/specs that I could follow for v3.0?

**Pull request closed without merging**
