### PR TITLE
Preparing for submissions

### PR DESCRIPTION
**Pull request by zvr**
The files in this repo are used to create **three** different editions of the Specification:

1. the one presented in HTML 
2. a PDF, to be submitted to OMG
3. a PDF, to be submitted to ISO

Unfortunately, the content is not exactly the same in all of them.

This PR:

- Moves files around to facilitate preparation of the 3 editions
- Updates mkdocs config to use new paths (for the first one)

Note:
There will be a fourth edition, a PDF version for SPDX website, but this content will very closely match the HTML one (1, above) and in any case is not ready right now.

### CODE REVIEW

**Review by goneall — APPROVED** [review]
Changes look reasonable to me with the caveat that I don't have much expertise in the mkdocs tooling.

**Comment by bact** [comment]
There are currently two warnings during validation:

```text
WARNING -  Doc file 'front/index.md' contains a link './licenses/Community-Spec-1.0.md', but the target 'front/licenses/Community-Spec-1.0.md' is not found among documentation files.

WARNING -  Doc file 'front/index.md' contains a link './licenses/CC-BY-3.0.md', but the target 'front/licenses/CC-BY-3.0.md' is not found among documentation files.
```

**Review by bact — CHANGES_REQUESTED** [review]
Links in Lines 9 and 13 may need to update:

- `./licenses/Community-Spec-1.0.md` -> `../licenses/Community-Spec-1.0.md`

- `./licenses/CC-BY-3.0.md` -> `../licenses/CC-BY-3.0.md`

**Comment by zvr** [comment]
It's unfortunate that mkdocs and LaTeX treat relative filenames differently...

On the other hand, we're fortunate that this is only on the `index` file, which is different in LaTeX editions anyway, so no harm done.

**Review by bact — APPROVED** [review]

**Pull request merged**
