### PR TITLE
Conformance: fix typo: refering -> referring

### PR DESCRIPTION
**Pull request by bact**
One minor typo in Conformance chapter.

- validation failed because https://github.com/spdx/spdx-spec/issues/1135
- please apply https://github.com/spdx/spdx-spec/pull/1133 first

### CODE REVIEW

**Comment by bact** [comment]
validation failed because #1135, please apply #1133 first.

**Comment by bobmartin3000** [comment]
Lgtm

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Arthit Suriyawongkul ***@***.***>
Sent: Saturday, October 12, 2024 5:47:20 AM
To: spdx/spdx-spec ***@***.***>
Cc: Robert A Martin ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [spdx/spdx-spec] Conformance: fix typo: refering -> referring (PR #1136)

@ bobmartin3000 fyi — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <spdx/spdx-spec/pull/1136/c2408481038@ github. com> ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍


@bobmartin3000<https://github.com/bobmartin3000> fyi

**Comment by bact** [comment]
Thank you Robert.

**Review by goneall — APPROVED** [review]

**Comment by bact** [comment]
With two approvals, I will merge this.

**Pull request merged**
